// Country flag mapping utility
export const getCountryFlag = (nationality: string): string => {
  const flagMap: { [key: string]: string } = {
    'Emirati': '🇦🇪',
    'British': '🇬🇧',
    'Canadian': '🇨🇦',
    'French': '🇫🇷',
    'German': '🇩🇪',
    'Italian': '🇮🇹',
    'Spanish': '🇪🇸',
    'Chinese': '🇨🇳',
    'Japanese': '🇯🇵',
    'Korean': '🇰🇷',
    'Indian': '🇮🇳',
    'Australian': '🇦🇺',
    'Brazilian': '🇧🇷',
    'Egyptian': '🇪🇬',
    'Saudi Arabian': '🇸🇦',
    'Turkish': '🇹🇷',
    'Greek': '🇬🇷',
    'Russian': '🇷🇺',
    'American': '🇺🇸',
    'Ukrainian': '🇺🇦',
    'Polish': '🇵🇱',
    'Dutch': '🇳🇱',
    'Swedish': '🇸🇪',
    'Norwegian': '🇳🇴',
    'Danish': '🇩🇰',
    'Finnish': '🇫🇮',
    'Swiss': '🇨🇭',
    'Austrian': '🇦🇹',
    'Belgian': '🇧🇪',
    'Portuguese': '🇵🇹',
    'Irish': '🇮🇪',
    'Israeli': '🇮🇱',
    'Lebanese': '🇱🇧',
    'Jordanian': '🇯🇴',
    'Kuwaiti': '🇰🇼',
    'Qatari': '🇶🇦',
    'Bahraini': '🇧🇭',
    'Omani': '🇴🇲',
    'Iraqi': '🇮🇶',
    'Iranian': '🇮🇷',
    'Pakistani': '🇵🇰',
    'Bangladeshi': '🇧🇩',
    'Sri Lankan': '🇱🇰',
    'Nepalese': '🇳🇵',
    'Afghan': '🇦🇫',
    'Thai': '🇹🇭',
    'Vietnamese': '🇻🇳',
    'Indonesian': '🇮🇩',
    'Malaysian': '🇲🇾',
    'Singaporean': '🇸🇬',
    'Filipino': '🇵🇭',
    'South African': '🇿🇦',
    'Nigerian': '🇳🇬',
    'Kenyan': '🇰🇪',
    'Moroccan': '🇲🇦',
    'Tunisian': '🇹🇳',
    'Algerian': '🇩🇿',
    'Libyan': '🇱🇾',
    'Sudanese': '🇸🇩',
    'Ethiopian': '🇪🇹',
    'Ghanaian': '🇬🇭',
    'Senegalese': '🇸🇳',
    'Mexican': '🇲🇽',
    'Brazilian': '🇧🇷',
    'Argentinian': '🇦🇷',
    'Chilean': '🇨🇱',
    'Colombian': '🇨🇴',
    'Peruvian': '🇵🇪',
    'Venezuelan': '🇻🇪',
    'Ecuadorian': '🇪🇨',
    'Bolivian': '🇧🇴',
    'Paraguayan': '🇵🇾',
    'Uruguayan': '🇺🇾',
    'Other': '🏳️'
  }
  
  return flagMap[nationality] || '🏳️'
}

// Get nationality from country name (for reverse lookup)
export const getNationalityFromCountry = (country: string): string => {
  const countryToNationality: { [key: string]: string } = {
    'United Arab Emirates': 'Emirati',
    'United Kingdom': 'British',
    'Canada': 'Canadian',
    'France': 'French',
    'Germany': 'German',
    'Italy': 'Italian',
    'Spain': 'Spanish',
    'China': 'Chinese',
    'Japan': 'Japanese',
    'South Korea': 'Korean',
    'India': 'Indian',
    'Australia': 'Australian',
    'Brazil': 'Brazilian',
    'Egypt': 'Egyptian',
    'Saudi Arabia': 'Saudi Arabian',
    'Turkey': 'Turkish',
    'Greece': 'Greek',
    'Russia': 'Russian',
    'United States': 'American',
    'Ukraine': 'Ukrainian',
    'Poland': 'Polish',
    'Netherlands': 'Dutch',
    'Sweden': 'Swedish',
    'Norway': 'Norwegian',
    'Denmark': 'Danish',
    'Finland': 'Finnish',
    'Switzerland': 'Swiss',
    'Austria': 'Austrian',
    'Belgium': 'Belgian',
    'Portugal': 'Portuguese',
    'Ireland': 'Irish',
    'Israel': 'Israeli',
    'Lebanon': 'Lebanese',
    'Jordan': 'Jordanian',
    'Kuwait': 'Kuwaiti',
    'Qatar': 'Qatari',
    'Bahrain': 'Bahraini',
    'Oman': 'Omani',
    'Iraq': 'Iraqi',
    'Iran': 'Iranian',
    'Pakistan': 'Pakistani',
    'Bangladesh': 'Bangladeshi',
    'Sri Lanka': 'Sri Lankan',
    'Nepal': 'Nepalese',
    'Afghanistan': 'Afghan',
    'Thailand': 'Thai',
    'Vietnam': 'Vietnamese',
    'Indonesia': 'Indonesian',
    'Malaysia': 'Malaysian',
    'Singapore': 'Singaporean',
    'Philippines': 'Filipino',
    'South Africa': 'South African',
    'Nigeria': 'Nigerian',
    'Kenya': 'Kenyan',
    'Morocco': 'Moroccan',
    'Tunisia': 'Tunisian',
    'Algeria': 'Algerian',
    'Libya': 'Libyan',
    'Sudan': 'Sudanese',
    'Ethiopia': 'Ethiopian',
    'Ghana': 'Ghanaian',
    'Senegal': 'Senegalese',
    'Mexico': 'Mexican',
    'Argentina': 'Argentinian',
    'Chile': 'Chilean',
    'Colombia': 'Colombian',
    'Peru': 'Peruvian',
    'Venezuela': 'Venezuelan',
    'Ecuador': 'Ecuadorian',
    'Bolivia': 'Bolivian',
    'Paraguay': 'Paraguayan',
    'Uruguay': 'Uruguayan'
  }
  
  return countryToNationality[country] || 'Other'
}
